services:
  - type: web
    name: telegram-payment-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_webhook.py"
    envVars:
      - key: TOKEN
        value: PASTE_YOUR_BOT_TOKEN_HERE